### ISSUE TITLE
Calling `set` in rapid succession loses some of the elements

### ISSUE THREAD

**Issue by plentylife** [gundb/gun-level#47]
When calling `set` on the same node in close succession does not save all elements to the database

For example when calling set 3 times in a row:
I can clearly see, with breakpoints how one of the elements is in one `batch` (which does NOT get written), and the other two are in a different `batch` (which does get written)

https://github.com/PsychoLlama/gun-level/blob/master/src/Adapter/index.js#L160

**Comment by amark** [comment]
@plentylife batching is a ... pain.

In the future, I think the smartest thing to do will be to switch most of these storage drivers over to the RSE engine which properly handles/abstract logic like that (batching, merging, chunking, etc.), you interested in helping?

**Comment by plentylife** [comment]
@amark I would like to, but I'm just totally unable.

As far as the bug goes, I've investigated it further and:
- Setting debug points in different places gives me anything from a proper save, to only one of the elements being saved.
- I sometimes see the variable `merge` equal to 1, before any of the breakpoints where it could possibly be incremented are hit. It makes no sense to me; should be 0, in the (debugger) scope variables it's 0, but in the watch it's 1.

**Comment by plentylife** [comment]
Let me know if you need a reproduction snippet

**Comment by plentylife** [comment]
I looked at the task of porting stuff to Radix (which took me a while to figure out what it was), and wouldn't I be able to just shamelessly plagirize https://github.com/amark/gun/blob/master/lib/rs3.js replacing the appropriate `s3` functions with `levelup` functions?

**Comment by amark** [comment]
@plentylife yes! Quite possibly!!!! That is the goal.

Sorry for the delay, I didn't notice that my email inbox had re-sent this as updates since your original comment.

**Comment by plentylife** [comment]
I tried with RaDisk, to no avail.

**Comment by plentylife** [comment]
That is, I tried converting RaDisk to use Level to no avail.
I also tried using an `fs` library for the browser (that would save to
indexeddb), and vanilla radisk was broken.
So I just gave up.

**Comment by amark** [comment]
@plentylife could you by chance send me the errors that you were getting? I can help adjust/fix/tweak things so that they work, and I'd super appreciate your contributions!

**Comment by plentylife** [comment]
The final issue was that entries would get saved under `!` key, and not the id that I would give them.

**Comment by amark** [comment]
@plentylife that is intentional! The `!` is a file "chunk" that stores data inside of it.

If you open up the `!` file, you'll see that your data with its key is stored inside of it.

As the file gets larger and larger, the Radix Storage Engine scales up the data into different file "chunks" that will have different names than `!`.

Is there a particular reason you  need/want every record to have its own file? (And even if you do, do you know that that would not be scalable? Are you okay with that?)

**Comment by plentylife** [comment]
What about using databases?
I was trying to do this for LevelUp, that would then have IndexedDB as it's
backend.
Shouldn't each key-value pair have it's own key?

**Comment by plentylife** [comment]
I understand now!

I'll be honest, I gave up and ended up using a different database, which is
unfortunate because gun was perfect.
The main reason I gave up is because the code is very obscure and poorly
commented.
Coming to a new codebase, the last thing you want to see is little comments
and obscure variable names.

I understand that this is a ton of work, and there's little time for
comments and long variable names, but those pieces are crucial if you want
to attract help.

**Comment by amark** [comment]
Given that gun is one of the most popular databases on GitHub and we have a huge community of people already building adapters and connectors and helping, it is okay if you don't like the code. Good luck finding code that can perform 20M+ ops/sec on low end laptops and has all the key features as gun, let alone is MIT open source and full of friendly contributors and maintainers. If you want that, you'll probably have to spend the next 5 years building it yourself. Cheers!
